services:
  deep-research:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./results:/app/results
      - ./search_results:/app/search_results
    env_file:
      - .env
    ports:
      - "7860:7860"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    # Command will be overridden by ENTRYPOINT in Dockerfile
    # Override entrypoint if needed: entrypoint: ["sh", "-c", "sleep infinity"] 